# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55a6fe5e67b59a6338ecb951af13694d2859b3ab7a1ae4afbd43dacbf0b9016e070a65d53d9f277e7a54d3bfa8fc114609090e9141969091a784c560c0236666

test:
  secret_key_base: 22b98af05c24a04f6a840e90e060b5b41f618235dcda94b0bca0ef2b7661da1727365114a457c4fe978ef0b265051267982f14ec657f3636537f3c5d107913d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
